// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020-2026 Michal Dengusiak & Jakub Ziolkowski and contributors

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;
using Xunit;

namespace SAM.Tests
{
    /// <summary>
    /// Integrity and sanitisation of the GenOpt 3.1.1 oracle fixtures in Golden/GenOpt
    /// (generated by SAM.Tests.GenOptOracle; see documentation/GenOpt-3.1.1-Behaviour.md).
    /// The fixtures must stay synthetic: no machine paths, user or company names, Tas material,
    /// or GenOpt licence header text (only data rows are stored).
    /// </summary>
    public class GenOptOracleFixtureTests
    {
        private static readonly string Directory_GenOpt = Path.Combine(AppContext.BaseDirectory, "Golden", "GenOpt");

        private static readonly Regex[] Forbidden =
        {
            new Regex(@"[A-Za-z]:[\\/]", RegexOptions.Compiled),
            new Regex(@"(?i)[\\/]Users[\\/]", RegexOptions.Compiled),
            new Regex(@"(?i)AppData|Program Files|OneDrive|scratchpad|[\\/]Temp[\\/]", RegexOptions.Compiled),
            new Regex(@"(?i)Environmental Design Solutions|TasGenExecute|TasGenOpt|\.tbd\b|\.tpd\b|\.tsd\b|\.t3d\b", RegexOptions.Compiled),
            new Regex(@"(?i)Lawrence Berkeley|Copyright|All rights reserved", RegexOptions.Compiled),
            new Regex(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", RegexOptions.Compiled),
        };

        public static IEnumerable<object[]> FixtureFiles()
        {
            return Directory.GetFiles(Directory_GenOpt).OrderBy(f => f, StringComparer.Ordinal).Select(f => new object[] { Path.GetFileName(f) });
        }

        [Fact]
        public void Fixtures_ArePresent()
        {
            Assert.True(Directory.Exists(Directory_GenOpt), "Golden/GenOpt is not copied to the test output.");
            Assert.True(Directory.GetFiles(Directory_GenOpt, "*.json").Length >= 31);
            Assert.True(File.Exists(Path.Combine(Directory_GenOpt, "float-rounding-java8.tsv")));
        }

        [Theory]
        [MemberData(nameof(FixtureFiles))]
        public void Fixture_ContainsNoMachineOrProprietaryData(string fileName)
        {
            string[] lines = File.ReadAllLines(Path.Combine(Directory_GenOpt, fileName));
            for (int i = 0; i < lines.Length; i++)
            {
                foreach (Regex regex in Forbidden)
                {
                    Assert.False(regex.IsMatch(lines[i]), string.Format("{0} line {1} matches '{2}': {3}", fileName, i + 1, regex, lines[i]));
                }
            }
        }

        [Theory]
        [MemberData(nameof(FixtureFiles))]
        public void Trace_IsWellFormed(string fileName)
        {
            if (!fileName.EndsWith(".json", StringComparison.Ordinal))
            {
                return;
            }

            using JsonDocument document = JsonDocument.Parse(File.ReadAllText(Path.Combine(Directory_GenOpt, fileName)));
            JsonElement root = document.RootElement;
            JsonElement genOptCase = root.GetProperty("case");
            Assert.Equal(Path.GetFileNameWithoutExtension(fileName), genOptCase.GetProperty("name").GetString());

            int parameters = genOptCase.GetProperty("parameters").GetArrayLength();
            int outputs = genOptCase.GetProperty("function").GetProperty("outputs").GetArrayLength();
            Assert.True(root.GetProperty("termination").GetArrayLength() > 0);

            // Owner decision D4: data rows, comments and termination text only; no GenOpt console transcript.
            Assert.False(root.TryGetProperty("console", out _), "golden traces must not store the GenOpt console transcript");

            foreach (string listing in new[] { "all", "main" })
            {
                int previousSimulation = 0;
                foreach (JsonElement row in root.GetProperty(listing).EnumerateArray())
                {
                    int simulation = row.GetProperty("simulation").GetInt32();
                    Assert.True(simulation >= 0);
                    if (listing == "all")
                    {
                        Assert.True(simulation >= previousSimulation - 1000, "simulation numbers out of order");
                    }

                    previousSimulation = simulation;
                    Assert.Equal(outputs, row.GetProperty("f").GetArrayLength());
                    Assert.Equal(parameters, row.GetProperty("x").GetArrayLength());
                    foreach (JsonElement value in row.GetProperty("f").EnumerateArray().Concat(row.GetProperty("x").EnumerateArray()))
                    {
                        Assert.True(double.TryParse(value.GetString(), NumberStyles.Float, CultureInfo.InvariantCulture, out _), "not a number: " + value.GetString());
                    }
                }
            }
        }

        [Fact]
        public void FloatRoundingFixture_IsWellFormed()
        {
            string[] notes = { "shortest", "not-shortest", "not-shortest-integer", "unmodelled" };
            int rows = 0;
            foreach (string line in File.ReadLines(Path.Combine(Directory_GenOpt, "float-rounding-java8.tsv")))
            {
                if (line.StartsWith("#", StringComparison.Ordinal) || line.StartsWith("floatBits", StringComparison.Ordinal))
                {
                    continue;
                }

                string[] cells = line.Split('\t');
                Assert.Equal(3, cells.Length);
                Assert.Matches("^[0-9A-F]{8}$", cells[0]);
                Assert.True(double.TryParse(cells[1], NumberStyles.Float, CultureInfo.InvariantCulture, out _), cells[1]);
                Assert.Contains(cells[2], notes);
                rows++;
            }

            Assert.True(rows > 3000);
        }
    }
}
